-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 09:15:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kurachiweb_ichimondev
-- -----------------------------------------------------
-- 1問の開発用DB

-- -----------------------------------------------------
-- Schema kurachiweb_ichimondev
--
-- 1問の開発用DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kurachiweb_ichimondev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `kurachiweb_ichimondev` ;

-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アカウント基本ID',
  `nickname` VARCHAR(210) NOT NULL COMMENT '表示用ニックネーム',
  `self_intro` VARCHAR(2046) NOT NULL COMMENT '自己紹介',
  `registered_at` DATETIME NOT NULL COMMENT 'アカウント登録完了日時',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `account_nickname_idx` (`nickname` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'アカウント基本情報';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`survey` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`survey` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アンケートID',
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント基本ID',
  `greeting` VARCHAR(2046) NULL DEFAULT NULL COMMENT 'アンケートの回答者に表示される、「ご協力ください」といった短文',
  `title` VARCHAR(255) NULL DEFAULT NULL COMMENT 'タイトル、一覧表示で目立つ表示となる',
  `description` VARCHAR(2046) NULL DEFAULT NULL COMMENT '説明',
  `publish_start` DATETIME NOT NULL COMMENT 'アンケート公開開始日',
  `publish_end` DATETIME NOT NULL COMMENT 'アンケート公開終了日',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_survey_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_survey_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケート\nタイトルや質問項目などから成る';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`question` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`question` (
  `id` VARCHAR(31) NOT NULL COMMENT '質問ID',
  `survey_id` VARCHAR(31) NOT NULL COMMENT '対象のアンケートID',
  `type` TINYINT UNSIGNED NOT NULL COMMENT '質問の種類\n1:1行テキスト\n2:複数行テキスト\n3:チェックボックス\n4:ラジオボタン\n5:プルダウン形式選択',
  `description` VARCHAR(2046) NULL DEFAULT NULL COMMENT '質問文',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `fk_question_survey_idx` (`survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_survey`
    FOREIGN KEY (`survey_id`)
    REFERENCES `kurachiweb_ichimondev`.`survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケートの質問項目';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`question_choice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`question_choice` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`question_choice` (
  `id` VARCHAR(31) NOT NULL COMMENT '回答選択肢ID\n1以上のランダム値\n不変',
  `question_id` VARCHAR(31) NOT NULL COMMENT '対象の質問ID',
  `label` VARCHAR(255) NOT NULL COMMENT 'フロント用選択肢ラベル',
  `value` INT UNSIGNED NOT NULL COMMENT 'フロント用選択肢ID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_question_choice_question_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_choice_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `kurachiweb_ichimondev`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '質問に対する回答項目';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`answer` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`answer` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アンケートへの回答ID',
  `question_id` VARCHAR(31) NOT NULL COMMENT '対象の質問ID',
  `choice_value` INT UNSIGNED NULL DEFAULT NULL COMMENT '選んだ選択肢\n自由入力型ではNULL',
  `text` TEXT NULL DEFAULT NULL COMMENT '回答における記述内容\n選択式ではNULL',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `kurachiweb_ichimondev`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケートへの回答';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_publish_url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_publish_url` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_publish_url` (
  `id` VARCHAR(31) NOT NULL COMMENT 'カテゴリID\n1以上のランダム値\n不変',
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント基本ID',
  `url` VARCHAR(1022) NOT NULL COMMENT '公開先のURL',
  `sort_priority` INT UNSIGNED NOT NULL COMMENT 'ソート順位',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_setting_url_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_setting_url_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントの持ち主が管理する、アンケートの公開対象URL';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`language` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`language` (
  `id` INT UNSIGNED NOT NULL COMMENT '表示言語ID',
  `name` VARCHAR(127) NOT NULL COMMENT '表示言語名',
  `sort_priority` INT UNSIGNED NOT NULL COMMENT 'ソート順位',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '表示言語リファレンス';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`timezone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`timezone` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`timezone` (
  `id` INT UNSIGNED NOT NULL COMMENT '都道府県ID',
  `name` VARCHAR(127) NOT NULL COMMENT 'タイムゾーン名',
  `sort_priority` INT UNSIGNED NOT NULL COMMENT 'ソート順位',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'タイムゾーンリファレンス';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`answer_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`answer_token` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`answer_token` (
  `token` VARCHAR(768) NOT NULL COMMENT 'アンケート表示リクエストの際に発行されたトークン',
  `survey_id` VARCHAR(31) NOT NULL COMMENT '対象のアンケートID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`token`),
  INDEX `fk_answer_token_survey_idx` (`survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_token_survey`
    FOREIGN KEY (`survey_id`)
    REFERENCES `kurachiweb_ichimondev`.`survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT
COMMENT = 'アンケートへの回答リクエストが正当であるかを検証する、照合トークンリスト。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_auth` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_auth` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アカウント認証ID',
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント基本ID',
  `email` VARCHAR(628) NOT NULL COMMENT 'メールアドレスの暗号化済み文字列\n復号して利用できる',
  `email_hash` VARCHAR(128) NOT NULL COMMENT 'メールアドレスのハッシュ文字列\nメールアドレスが他のアカウントで使われているかの判定用',
  `verified_email` SMALLINT UNSIGNED NOT NULL COMMENT 'メールアドレスの存在が確認されたか\n0:未認証 1:認証手続き中 2:認証済',
  `password` VARCHAR(255) NOT NULL COMMENT 'パスワード',
  `password_updated_at` DATETIME NOT NULL COMMENT 'パスワードの最終更新日時',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_auth_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `email_hash_UNIQUE` (`email_hash` ASC) VISIBLE,
  CONSTRAINT `fk_account_auth_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT
COMMENT = 'アカウント認証情報\n基本的に、1回の更新で1種類のデータしか更新しないように、アプリケーション層で制御する。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`verify_email_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`verify_email_token` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`verify_email_token` (
  `token` VARCHAR(768) NOT NULL COMMENT 'メールアドレス認証リクエストの際に発行されたトークン',
  `account_id` VARCHAR(31) NOT NULL COMMENT '認証対象のアカウント基本ID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`token`),
  INDEX `fk_verify_email_token_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_verify_email_token_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT
COMMENT = 'アカウントのメールアドレス認証リクエストが正当であるかを検証する、照合トークンリスト。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_login_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_login_session` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_login_session` (
  `id` VARCHAR(31) NOT NULL COMMENT 'セッションID',
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント基本ID',
  `token_hash` VARCHAR(510) NOT NULL COMMENT 'トークンのハッシュ文字列',
  `ip_address` VARCHAR(255) NULL COMMENT 'IPアドレスの暗号化文字列',
  `user_agent` TEXT NULL COMMENT 'ユーザーエージェントの暗号化文字列',
  `last_login_at` DATETIME NOT NULL COMMENT '最終ログイン日時',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_login_session_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `account_login_session_token_hash_idx` (`token_hash` ASC) VISIBLE,
  CONSTRAINT `fk_account_login_session_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT
COMMENT = 'アカウントのログインセッションを保持';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_styling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_styling` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_styling` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アカウントスタイル設定ID',
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント基本ID',
  `font_size` INT NOT NULL COMMENT 'フォントの大きさ\npx値の等倍',
  `header_size` SMALLINT NOT NULL COMMENT 'ヘッダーの大きさ\n1: 小さい\n2: デフォルト',
  `language` INT NOT NULL COMMENT '表示言語',
  `timezone` INT NOT NULL COMMENT '時刻表示におけるタイムゾーン',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_style_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `header_size_UNIQUE` (`header_size` ASC) VISIBLE,
  UNIQUE INDEX `timezone_UNIQUE` (`timezone` ASC) VISIBLE,
  UNIQUE INDEX `language_UNIQUE` (`language` ASC) VISIBLE,
  UNIQUE INDEX `font_size_UNIQUE` (`font_size` ASC) VISIBLE,
  CONSTRAINT `fk_account_style_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントごとに管理する、表示設定\nフォントサイズ設定など。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_notification` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_notification` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アカウント通知設定ID',
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント基本ID',
  `way` SMALLINT UNSIGNED NOT NULL COMMENT '通知手段\nサービス内通知やメール通知',
  `trigger` SMALLINT UNSIGNED NOT NULL COMMENT '通知トリガーの発生タイミング',
  `enabled` SMALLINT UNSIGNED NOT NULL COMMENT 'その通知トリガーは有効か',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_setting_notification_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_setting_notification_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントの通知設定';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_profile_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_profile_image` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_profile_image` (
  `id` VARCHAR(31) NOT NULL COMMENT 'アカウントプロフィール画像設定ID',
  `account_id` VARCHAR(31) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL COMMENT 'プロフィール画像のURL',
  `selected` SMALLINT UNSIGNED NOT NULL COMMENT '現在使用されているプロフィール画像か',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_setting_icon_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_setting_icon_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントのプロフィール画像設定';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`change_email_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`change_email_token` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`change_email_token` (
  `token` VARCHAR(768) NOT NULL COMMENT 'メールアドレス変更リクエストの際に発行されたトークン',
  `account_id` VARCHAR(31) NOT NULL COMMENT '認証対象のアカウント基本ID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`token`),
  INDEX `fk_change_email_token_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_change_email_token_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントのメールアドレス変更リクエストが正当であるかを検証する、照合トークンリスト。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`change_password_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`change_password_token` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`change_password_token` (
  `token` VARCHAR(768) NOT NULL COMMENT 'パスワード変更リクエストの際に発行されたトークン',
  `account_id` VARCHAR(31) NOT NULL COMMENT '認証対象のアカウント基本ID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`token`),
  INDEX `fk_change_password_token_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_change_password_token_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントのパスワード変更リクエストが正当であるかを検証する、照合トークンリスト。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`delete_account_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`delete_account_token` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`delete_account_token` (
  `token` VARCHAR(768) NOT NULL COMMENT 'アカウント削除リクエストの際に発行されたトークン',
  `account_id` VARCHAR(31) NOT NULL COMMENT '認証対象のアカウント基本ID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`token`),
  INDEX `fk_delete_account_token_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_delete_account_token_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントの削除リクエストが正当であるかを検証する、照合トークンリスト。';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`survey_publish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`survey_publish` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`survey_publish` (
  `id` VARCHAR(31) NOT NULL,
  `survey_id` VARCHAR(31) NOT NULL COMMENT '対象のアンケートID',
  `account_url_id` VARCHAR(31) NOT NULL COMMENT 'アンケートの公開対象URL',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_survey_publish_survey_idx` (`survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_survey_publish_survey`
    FOREIGN KEY (`survey_id`)
    REFERENCES `kurachiweb_ichimondev`.`survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケートを公開する対象URL';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`account_security_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`account_security_log` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`account_security_log` (
  `id` VARCHAR(31) NOT NULL,
  `account_id` VARCHAR(31) NOT NULL COMMENT '対象のアカウント情報ID',
  `type` SMALLINT UNSIGNED NOT NULL COMMENT 'アカウントセキュリティログの種類\n1:新規登録 2: アカウント削除 11: ログイン 12:他のセッションからログアウト 21:メールアドレスを認証 22:メールアドレスの変更 23:パスワードの変更',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_account_security_log_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_security_log_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `kurachiweb_ichimondev`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アカウントのセキュリティログ\nログインやパスワード変更など';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
