version: "3.8"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "55001:55001"
      - "24678:24678" # Viteの無限リロード対策
    volumes:
      - type: volume
        source: ichimon-frontend
        target: /usr/src/app
        volume:
          nocopy: true
      - type: bind
        source: ../frontend
        target: /usr/src/app
  backend:
    env_file: ../backend/.env
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "55002:8000"
    volumes:
      - type: volume
        source: ichimon-backend
        target: /usr/src/app
        volume:
          nocopy: true
      - type: bind
        source: ../backend
        target: /usr/src/app
  database:
    env_file: ../database/.env
    build:
      context: ../database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: ichimon-database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ../database
        target: /usr/src/db
  redis:
    build:
      context: ../redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: ichimon-redis
        target: /usr/local/etc/redis
        volume:
          nocopy: true
      - type: bind
        source: ../redis
        target: /usr/src/db
volumes:
  ichimon-frontend:
    name: ichimon-frontend
  ichimon-backend:
    name: ichimon-backend
  ichimon-database:
    name: ichimon-database
  ichimon-redis:
    name: ichimon-redis
