-- MySQL Script generated by MySQL Workbench
-- Tue Mar  1 20:50:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kurachiweb_ichimondev
-- -----------------------------------------------------
-- 1問の開発用DB

-- -----------------------------------------------------
-- Schema kurachiweb_ichimondev
--
-- 1問の開発用DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kurachiweb_ichimondev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `kurachiweb_ichimondev` ;

-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`user` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`user` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '内部ID\n1以上のランダム値\n不変',
  `display_id` VARCHAR(32) NOT NULL COMMENT 'ユーザーID\n公開情報\nデータはユーザーが変更できる',
  `name` VARCHAR(510) NULL DEFAULT NULL COMMENT 'ユーザー名\n会員は必須',
  `mail_address` VARCHAR(255) NULL DEFAULT NULL COMMENT 'メールアドレス\n会員は必須',
  `mail_address_alter` VARCHAR(255) NULL DEFAULT NULL COMMENT 'メールアドレス\n主とするメールアドレスが使えなくなった場合の連絡用',
  `password` VARCHAR(255) NULL DEFAULT NULL COMMENT 'パスワード\n会員は必須',
  `password_updated_at` DATE NULL DEFAULT NULL COMMENT 'パスワードの最終更新日',
  `tel_no` VARCHAR(30) NULL DEFAULT NULL COMMENT '自宅電話番号または携帯電話番号または勤務先電話番号',
  `address` VARCHAR(1022) NULL DEFAULT NULL COMMENT '住所\n会員は必須',
  `address_bill` VARCHAR(1022) NULL DEFAULT NULL COMMENT '請求先住所',
  `registered_at` DATETIME NULL DEFAULT NULL COMMENT '会員登録日時',
  `subscription_id` VARCHAR(45) NULL COMMENT 'StripeサブスクリプションID\n有料プラン登録済みなら必須\n解約時に必要',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_address_UNIQUE` (`mail_address` ASC),
  UNIQUE INDEX `display_id_UNIQUE` (`display_id` ASC),
  INDEX `tel_no` (`tel_no` ASC))
ENGINE = InnoDB
COMMENT = 'ユーザー';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`category` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`category` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'カテゴリID\n1以上のランダム値\n不変',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT 'カテゴリを設定したユーザーのID',
  `name` VARCHAR(31) NOT NULL COMMENT 'カテゴリ名',
  `sort_no` INT UNSIGNED NOT NULL COMMENT 'ソート番号',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'カテゴリ';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`survey` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`survey` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'アンケートID\n1以上のランダム値\n不変',
  `title` VARCHAR(63) NULL DEFAULT NULL COMMENT 'タイトル',
  `description_before` VARCHAR(2046) NULL DEFAULT NULL COMMENT '説明',
  `category_id` BIGINT UNSIGNED NOT NULL COMMENT 'カテゴリーID',
  `notice_after` VARCHAR(2046) NULL DEFAULT NULL COMMENT '設問後の補足文章',
  `creator_id` BIGINT UNSIGNED NOT NULL COMMENT 'アンケートを作成したユーザーのID',
  `notice_user_id` BIGINT UNSIGNED NOT NULL COMMENT 'アンケートに関して通知するユーザーのID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_survey_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_survey_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `kurachiweb_ichimondev`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケート\nタイトルや質問項目などから成る';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`question` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`question` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '質問ID\n1以上のランダム値\n不変',
  `survey_id` BIGINT UNSIGNED NOT NULL COMMENT 'アンケートID',
  `type` TINYINT UNSIGNED NOT NULL COMMENT '質問の種類\n1:1行テキスト\n2:複数行テキスト\n3:チェックボックス\n4:ラジオボタン\n5:プルダウン形式選択',
  `description` VARCHAR(2046) NULL DEFAULT NULL COMMENT '質問文',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `type` (`type` ASC),
  INDEX `fk_question_survey_idx` (`survey_id` ASC),
  CONSTRAINT `fk_question_survey`
    FOREIGN KEY (`survey_id`)
    REFERENCES `kurachiweb_ichimondev`.`survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケートの質問項目';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`question_choice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`question_choice` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`question_choice` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '回答選択肢ID\n1以上のランダム値\n不変',
  `question_id` BIGINT UNSIGNED NOT NULL,
  `label` VARCHAR(255) NOT NULL COMMENT 'フロント用選択肢ラベル',
  `value` INT UNSIGNED NOT NULL COMMENT 'フロント用選択肢ID',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_question_choice_question_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_choice_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `kurachiweb_ichimondev`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '質問に対する回答項目';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`answer` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`answer` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT 'アンケートへの回答ID',
  `question_id` BIGINT UNSIGNED NOT NULL COMMENT '質問ID',
  `choice_value` INT UNSIGNED NULL DEFAULT NULL COMMENT '選んだ選択肢\n自由入力型ではNULL',
  `text` VARCHAR(16000) NULL DEFAULT NULL COMMENT '回答における記述内容\n選択式ではNULL',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question_idx` (`question_id` ASC),
  CONSTRAINT `fk_answer_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `kurachiweb_ichimondev`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'アンケートへの回答';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`question_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`question_type` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`question_type` (
  `id` INT NOT NULL COMMENT '回答形式ID',
  `name` VARCHAR(31) NOT NULL COMMENT '回答形式名',
  `sort_id` INT UNSIGNED NOT NULL COMMENT 'ソート順位',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '回答形式リファレンス';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`prefecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`prefecture` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`prefecture` (
  `id` INT NOT NULL COMMENT '都道府県ID',
  `name` VARCHAR(7) NOT NULL COMMENT '都道府県名',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '都道府県リファレンス';


-- -----------------------------------------------------
-- Table `kurachiweb_ichimondev`.`survey_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kurachiweb_ichimondev`.`survey_token` ;

CREATE TABLE IF NOT EXISTS `kurachiweb_ichimondev`.`survey_token` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(3072) NOT NULL COMMENT 'アンケート表示レスポンスの際に発行されたトークン',
  `created_at` DATETIME NOT NULL COMMENT 'データ作成日時',
  `updated_at` DATETIME NOT NULL COMMENT 'データ更新日時',
  `deleted_at` DATETIME NULL DEFAULT NULL COMMENT 'データ削除日時',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin
COMMENT = 'アンケートへの回答リクエストが正当であるかを検証する、照合トークンリスト。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
